export default {
  login: 'Papa-Sean',
  id: 69025655,
  node_id: 'MDQ6VXNlcjY5MDI1NjU1',
  avatar_url: 'https://avatars.githubusercontent.com/u/69025655?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Papa-Sean',
  html_url: 'https://github.com/Papa-Sean',
  followers_url: 'https://api.github.com/users/Papa-Sean/followers',
  following_url:
    'https://api.github.com/users/Papa-Sean/following{/other_user}',
  gists_url: 'https://api.github.com/users/Papa-Sean/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/Papa-Sean/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Papa-Sean/subscriptions',
  organizations_url: 'https://api.github.com/users/Papa-Sean/orgs',
  repos_url: 'https://api.github.com/users/Papa-Sean/repos',
  events_url: 'https://api.github.com/users/Papa-Sean/events{/privacy}',
  received_events_url: 'https://api.github.com/users/Papa-Sean/received_events',
  type: 'User',
  site_admin: false,
  name: 'Papa-Sean',
  company: 'DetriDesoyeign',
  blog: 'www.paradizofilms.com',
  location: 'Detroit',
  email: 'papa@papasean.com',
  hireable: 'Yes',
  bio: 'What Up Doe!',
  twitter_username: 'papa-sean',
  public_repos: 76,
  public_gists: 0,
  followers: 7,
  following: 1,
  created_at: '2020-07-31T03:16:12Z',
  updated_at: '2024-05-02T18:30:44Z',
};
